import json
from pathlib import Path
from datetime import datetime

import pandas as pd
import streamlit as st

EVENTS_PATH = Path("outputs/events.jsonl")
HEATMAP_PATH = Path("outputs/heatmap.png")


def read_events(path: Path) -> pd.DataFrame:
    """Read JSONL events into a dataframe. Skips malformed lines safely."""
    if not path.exists():
        return pd.DataFrame()

    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                # if a line was partially written, just ignore it
                continue

    if not rows:
        return pd.DataFrame()

    df = pd.DataFrame(rows)

    # normalize expected columns so the UI doesn't crash
    for col in ["type", "track_id", "zone", "tripwire", "direction"]:
        if col not in df.columns:
            df[col] = None

    df["ts"] = pd.to_numeric(df["ts"], errors="coerce")
    df = df.dropna(subset=["ts"]).copy()

    df["time"] = df["ts"].apply(lambda x: datetime.fromtimestamp(float(x)))
    df = df.sort_values("ts", ascending=False).reset_index(drop=True)
    return df


def nice_time(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M:%S")


def main():
    st.set_page_config(page_title="VisionGuard Dashboard", page_icon="👁️", layout="wide")

    st.title("👁️ VisionGuard — Event Dashboard")
    st.caption("Events are read from outputs/events.jsonl (generated by the tracker).")

    # Sidebar
    with st.sidebar:
        st.header("Controls")

        if st.button("🔄 Refresh now"):
            st.rerun()

        auto_refresh = st.toggle("Auto-refresh (every ~2s)", value=False)

        st.divider()
        st.write("**Files**")
        st.code(str(EVENTS_PATH), language="text")
        st.code(str(HEATMAP_PATH), language="text")

    df = read_events(EVENTS_PATH)

    if df.empty:
        st.warning("No events found yet.")
        st.info("Run the tracker first: `python -m src.main`  (then refresh this page)")
        return

    # Build filter options
    all_types = sorted([t for t in df["type"].dropna().unique().tolist()])
    # Track IDs might be numeric or strings depending on logger; sanitize
    track_values = df["track_id"].dropna().unique().tolist()
    track_ids = []
    for v in track_values:
        try:
            track_ids.append(int(v))
        except Exception:
            pass
    track_ids = sorted(list(set(track_ids)))

    # Filters (sidebar)
    with st.sidebar:
        st.divider()
        st.subheader("Filters")

        selected_types = st.multiselect(
            "Event types",
            options=all_types,
            default=all_types,
        )

        selected_tracks = st.multiselect(
            "Track IDs",
            options=track_ids,
            default=[],
        )

        min_time = df["time"].min()
        max_time = df["time"].max()

        start_dt, end_dt = st.slider(
            "Time range",
            min_value=min_time.to_pydatetime(),
            max_value=max_time.to_pydatetime(),
            value=(min_time.to_pydatetime(), max_time.to_pydatetime()),
        )

    # Apply filters
    filtered = df.copy()

    if selected_types:
        filtered = filtered[filtered["type"].isin(selected_types)]

    if selected_tracks:
        filtered = filtered[filtered["track_id"].apply(lambda x: str(x).isdigit() and int(x) in selected_tracks)]

    filtered = filtered[(filtered["time"] >= start_dt) & (filtered["time"] <= end_dt)]
    filtered = filtered.sort_values("ts", ascending=False).reset_index(drop=True)

    # Top metrics
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total events", int(len(df)))
    c2.metric("Filtered events", int(len(filtered)))
    c3.metric("Unique track IDs", int(df["track_id"].nunique()))
    c4.metric("Event types", int(df["type"].nunique()))

    st.divider()

    # Heatmap display
    st.subheader("Movement Heatmap")
    if HEATMAP_PATH.exists():
        st.image(
            str(HEATMAP_PATH),
            caption="Generated when you quit the tracker with 'q' (outputs/heatmap.png).",
            use_container_width=True,
        )
    else:
        st.info("No heatmap yet. Run the tracker and quit with 'q' to generate outputs/heatmap.png.")

    st.divider()

    # Charts
    left, right = st.columns([1.2, 1])

    with left:
        st.subheader("Events over time (by minute)")
        if len(filtered) == 0:
            st.info("No events in the current filter.")
        else:
            timeline = filtered.copy()
            timeline["minute"] = timeline["time"].dt.floor("min")
            counts = timeline.groupby(["minute", "type"]).size().reset_index(name="count")
            pivot = counts.pivot(index="minute", columns="type", values="count").fillna(0)
            st.line_chart(pivot)

    with right:
        st.subheader("Most active track IDs")
        if len(filtered) == 0:
            st.info("No events in the current filter.")
        else:
            top_tracks = (
                filtered.dropna(subset=["track_id"])
                .groupby("track_id")
                .size()
                .reset_index(name="events")
                .sort_values("events", ascending=False)
                .head(10)
            )
            # bar_chart wants a series
            st.bar_chart(top_tracks.set_index("track_id")["events"])

    st.divider()

    # Incident feed
    st.subheader("Incident feed")

    show_cols = [
        "time",
        "type",
        "track_id",
        "zone",
        "tripwire",
        "direction",
        "seconds_in_zone",
        "speed_px_s",
        "turns",
        "distance_px",
    ]
    for col in show_cols:
        if col not in filtered.columns:
            filtered[col] = None

    feed = filtered[show_cols].copy()
    feed["time"] = feed["time"].apply(nice_time)

    st.dataframe(feed, use_container_width=True, height=360)

    st.divider()

    # Summary + download
    st.subheader("Session summary")

    type_counts = filtered["type"].value_counts().reset_index()
    type_counts.columns = ["event_type", "count"]
    st.table(type_counts)

    summary_lines = []
    summary_lines.append("VisionGuard — Dashboard Summary\n")
    summary_lines.append(f"Generated: {nice_time(datetime.now())}\n\n")
    summary_lines.append(f"Events in filter: {len(filtered)}\n")
    summary_lines.append(f"Unique IDs in filter: {filtered['track_id'].nunique()}\n\n")
    summary_lines.append("Event counts:\n")
    for _, row in type_counts.iterrows():
        summary_lines.append(f"  - {row['event_type']}: {row['count']}\n")

    st.download_button(
        label="⬇️ Download summary.txt",
        data="".join(summary_lines),
        file_name="visionguard_summary.txt",
        mime="text/plain",
    )

    if auto_refresh:
        st.caption("Auto-refresh is on.")
        st.sleep(2)
        st.rerun()


if __name__ == "__main__":
    main()